.PHONY: migrate migrations run test shell

migrate:
	python manage.py migrate

migrations:
	python manage.py makemigrations

run:
	python manage.py runserver

test:
	python manage.py test apps

shell:
	python manage.py shell
