# Generated by Django 4.2.17 on 2026-03-07 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('commands', '0001_initial'),
        ('bikes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ride_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='bikes.bike')),
                ('end_dock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides_ended', to='stations.dock')),
                ('end_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides_ended', to='stations.station')),
                ('start_dock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides_started', to='stations.dock')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides_started', to='stations.station')),
                ('unlock_command', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ride', to='commands.command')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
    ]
