# Generated by Django 4.2.17 on 2026-03-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='suspected_return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
