# Generated by Django 4.2.17 on 2026-03-07 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('rides', '0001_initial'),
        ('bikes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='current_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rides.ride'),
        ),
        migrations.AddField(
            model_name='bike',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to='stations.station'),
        ),
    ]
