# Generated by Django 4.2.17 on 2026-03-07 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('bikes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('UNLOCK', 'Unlock')], default='UNLOCK', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='bikes.bike')),
                ('dock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='stations.dock')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='stations.station')),
            ],
            options={
                'db_table': 'commands',
            },
        ),
    ]
