import * as cdk from 'aws-cdk-lib';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as iot from 'aws-cdk-lib/aws-iot';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as fs from 'fs';
import * as path from 'path';
import { Construct } from 'constructs';

// Station IDs — must match simulator/fleet.yml
const STATION_IDS = ['S001', 'S002', 'S003', 'S004', 'S005'];

// certs-config.json is generated by scripts/provision-certs.sh.
// It maps station IDs to their IoT certificate ARNs:
//   { "S001": "arn:aws:iot:us-east-1:...:cert/...", ... }
const CERTS_CONFIG_PATH = path.join(__dirname, '../../certs/certs-config.json');

interface BikeshareIotStackProps extends cdk.StackProps {
  eventIngestionFn: lambda.Function;
}

export class BikeshareIotStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: BikeshareIotStackProps) {
    super(scope, id, props);

    const { eventIngestionFn } = props;

    // Allow IoT Core to invoke the event ingestion Lambda
    eventIngestionFn.addPermission('AllowIotCoreInvoke', {
      principal: new iam.ServicePrincipal('iot.amazonaws.com'),
      sourceAccount: this.account,
    });

    // Read certificate ARNs generated by provision-certs.sh.
    // If the file doesn't exist yet, Things and Policies are still created
    // but certificate attachments are skipped. Run provision-certs.sh then
    // redeploy to complete the attachments.
    const certsConfig: Record<string, string> = fs.existsSync(CERTS_CONFIG_PATH)
      ? JSON.parse(fs.readFileSync(CERTS_CONFIG_PATH, 'utf-8'))
      : {};

    if (Object.keys(certsConfig).length === 0) {
      cdk.Annotations.of(this).addWarning(
        'certs/certs-config.json not found. Run scripts/provision-certs.sh then redeploy to attach certificates.'
      );
    }

    // One IoT Thing + per-station Policy per station
    for (const stationId of STATION_IDS) {
      const thingName = `bikeshare-station-${stationId}`;
      const policyName = `bikeshare-station-${stationId}-policy`;

      const thing = new iot.CfnThing(this, `Thing-${stationId}`, {
        thingName,
      });

      // Per-station policy: each station can only access its own topics.
      // This is enforced by IoT Core using the certificate attached to each Thing.
      const policy = new iot.CfnPolicy(this, `Policy-${stationId}`, {
        policyName,
        policyDocument: {
          Version: '2012-10-17',
          Statement: [
            {
              Effect: 'Allow',
              Action: 'iot:Connect',
              Resource: `arn:aws:iot:${this.region}:${this.account}:client/${thingName}`,
            },
            {
              // Station may publish events and telemetry on its own topics only
              Effect: 'Allow',
              Action: 'iot:Publish',
              Resource: [
                `arn:aws:iot:${this.region}:${this.account}:topic/station/${stationId}/events`,
                `arn:aws:iot:${this.region}:${this.account}:topic/station/${stationId}/telemetry`,
              ],
            },
            {
              // Station may subscribe to its own command topic only
              Effect: 'Allow',
              Action: 'iot:Subscribe',
              Resource: `arn:aws:iot:${this.region}:${this.account}:topicfilter/station/${stationId}/cmd`,
            },
            {
              Effect: 'Allow',
              Action: 'iot:Receive',
              Resource: `arn:aws:iot:${this.region}:${this.account}:topic/station/${stationId}/cmd`,
            },
          ],
        },
      });

      // Attach certificate to Thing and Policy (only if cert has been provisioned).
      // addDependency() ensures CloudFormation creates the Thing/Policy before
      // attempting the attachment — without this, CF may try them in parallel and fail.
      const certArn = certsConfig[stationId];
      if (certArn) {
        const thingCertAttach = new iot.CfnThingPrincipalAttachment(this, `ThingCertAttach-${stationId}`, {
          thingName,
          principal: certArn,
        });
        thingCertAttach.addDependency(thing);

        const policyCertAttach = new iot.CfnPolicyPrincipalAttachment(this, `PolicyCertAttach-${stationId}`, {
          policyName,
          principal: certArn,
        });
        policyCertAttach.addDependency(policy);
      }
    }

    // IoT Rule: station/+/events → event ingestion Lambda
    // topic(2) extracts the station ID from "station/S001/events" → "S001"
    new iot.CfnTopicRule(this, 'EventsRule', {
      ruleName: 'bikeshare_station_events',
      topicRulePayload: {
        sql: "SELECT *, topic(2) AS station_id FROM 'station/+/events'",
        awsIotSqlVersion: '2016-03-23',
        actions: [
          {
            lambda: { functionArn: eventIngestionFn.functionArn },
          },
        ],
        ruleDisabled: false,
      },
    });

    // IoT Rule: station/+/telemetry → event ingestion Lambda
    new iot.CfnTopicRule(this, 'TelemetryRule', {
      ruleName: 'bikeshare_station_telemetry',
      topicRulePayload: {
        sql: "SELECT *, topic(2) AS station_id FROM 'station/+/telemetry'",
        awsIotSqlVersion: '2016-03-23',
        actions: [
          {
            lambda: { functionArn: eventIngestionFn.functionArn },
          },
        ],
        ruleDisabled: false,
      },
    });

    // Handy reminder: the IoT endpoint isn't provisioned by CDK — it's account-wide
    new cdk.CfnOutput(this, 'IotEndpointCommand', {
      value: 'aws iot describe-endpoint --endpoint-type iot:Data-ATS --region us-east-1',
      description: 'Run this command to get the IoT Core endpoint for station/simulator config',
    });
  }
}
