# Generated by Django 4.2.17 on 2026-03-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='last_telemetry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
